{ inputs, ... }:
{
  # herdr (https://herdr.dev) manages terminal workspaces for coding agents.
  # The package comes from the herdr flake input rather than nixpkgs because
  # the yui theme relies on `[theme.custom.light]`/`[theme.custom.dark]`,
  # which need herdr >= 0.9.0.
  #
  # herdr reads exactly one config.toml and has no include mechanism, so the
  # theme fragment generated by yui is merged in here on the Nix side.
  flake.modules.homeManager.herdr =
    { pkgs, lib, ... }:
    let
      system = pkgs.stdenv.hostPlatform.system;
      yuiTheme = builtins.fromTOML (
        builtins.readFile "${inputs.yui.packages.${system}.herdr}/herdr/yui.toml"
      );
      # Keys under `theme` are owned by yui.
      settings = {
        ui = {
          # Shapes as well as colors for agent state.
          status_indicators = "symbols";
          # Notify through the outer terminal (ghostty) instead of in-app toasts.
          toast.delivery = "terminal";
          sound.enabled = false;
        };
      };
    in
    {
      home.packages = [ inputs.herdr.packages.${system}.default ];

      xdg.configFile."herdr/config.toml".source = (pkgs.formats.toml { }).generate "herdr-config.toml" (
        lib.recursiveUpdate settings yuiTheme
      );
    };
}
