#!/bin/sh

GIT_ROOT=$(git rev-parse --show-toplevel)
DOTS_NIXOS="$HOME/dotfiles/nix/hosts"

makeNixpkgs() {
    if ! test -d "$XDG_CONFIG_HOME"/nixpkgs; then
        mkdir -p "$XDG_CONFIG_HOME"/nixpkgs
    fi
}

case $(hostname) in
    fbs-work.local)
        makeNixpkgs

        ln -sf "$DOTS_NIXOS"/fbs-work.local/home.nix "$XDG_CONFIG_HOME"/nixpkgs/home.nix 

        "$GIT_ROOT"/scripts/stow.sh \
            ctags                   \
            alacritty_darwin        \
            emacs                   \
            git                     \
            nixpkgs                 \
            fish                    \
            pandoc                  \
            tmux
        ;;

    archminimal)
        makeNixpkgs

        ln -sf "$DOTS_NIXOS"/archminimal/home.nix "$XDG_CONFIG_HOME"/nixpkgs/home.nix 

        "$GIT_ROOT"/scripts/stow.sh \
            ctags                   \
            emacs                   \
            alacritty               \
            pam                     \
            pandoc                  \
            bspwm                   \
            rofi                    \
            sxhkd                   \
            picom                   \
            polybar                 \
            dunst                   \
            mime                    \
            x                       \
            tmux
        ;;
    nixos)
        makeNixpkgs

        ln -sf "$DOTS_NIXOS"/nixos/home.nix "$XDG_CONFIG_HOME"/nixpkgs/home.nix 
        sudo ln -sf "$DOTS_NIXOS"/nixos/configuration.nix /etc/nixos/configuration.nix

        "$GIT_ROOT"/scripts/stow.sh \
            ctags                   \
            emacs
        ;;
esac
