#!/usr/bin/env fish

if test (defaults read -g AppleInterfaceStyle) = "Dark"
  for socket in (ls $XDG_RUNTIME_DIR/nvim.*); nvim --server $socket --remote-send ':source ~/private/yui/colors/yui_dark.vim<CR>'; end
  fish ~/private/yui/fish/yui_dark.fish
  ~/private/yui/alacritty/yui_dark_msg.sh
else
  for socket in (ls $XDG_RUNTIME_DIR/nvim.*); nvim --server $socket --remote-send ':source ~/private/yui/colors/yui.vim<CR>'; end
  fish ~/private/yui/fish/yui.fish
  ~/private/yui/alacritty/yui_light_msg.sh
end
