#! /bin/sh

sxhkd &

dunst &

fcitx &

~/.fehbg &

xss-lock -- i3lock -n -i /data/wallpapers/kabaneri.png &

[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &

bspc monitor -d                    一 二 三 四 五 七

bspc config border_width           2
bspc config window_gap             0
bspc config normal_border_color    \#000000
bspc config focused_border_color   \#CB1B45

bspc config split_ratio            0.55
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config single_monocle         false

bspc rule -a                       Dunst state=floating
bspc rule -a                       Screenkey manage=off
bspc rule -a                       Zoom state=floating
