{ config, lib, pkgs, ... }:

with lib;
with types;
let
  cfg = config.programs.neovim;

in
{
  options = {
    programs.neovim = {
      ftPlugins = mkOption {
        type = attrsOf str;
        default = { };
        description = ''
          A mapping from filetype to vimscript code for that filetype.
        '';
        example = ''
          programs.neovim.ftPlugins = {
            css = ${''
            set suffixesadd+=.js,.jsx,.css
          ''};
          };
        '';
      };
    };
  };

  config = mkIf cfg.enable {
    xdg.configFile = (
      attrsets.mapAttrs'
        (ft: vimscript:
        attrsets.nameValuePair ("nvim/ftplugin/${ft}.vim") ({ text = ''
          " Generated by my Nix neovim module, all edits will be lost if not
          " made in the Nix source
          '' + vimscript; })
        )
        cfg.ftPlugins
    );
  };
}
