{ lib, pkgs, ... }:

with lib;
with types;

{
  options = {
    sources = mkOption
      {
        type = attrs;
        description = ''
          Path to the sources.nix generated by 'niv'.
        '';
        example = ''
          import (builtins.path { path = ./foo; name = "bar"; })
        '';
      };
  };
}
