name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: 0 8 * * *
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-vscode-extensions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        name: Install Nix
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          nix_path: https://github.com/NixOS/nixpkgs/archive/08ef0f28e3a41424b92ba1d203de64257a9fca6a.tar.gz
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Update Extensions
        run: cat shared_exts.txt | ./update_exts.sh > shared_exts.nix
        working-directory: modules/vscode

      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          add: 'modules/vscode/shared_exts.nix'
          default_author: github_actor
          message: 'Updated Visual Studio Code extensions'
          pull_strategy: 'NO-PULL'
