name: CI

on:
  schedule:
    - cron: 0 8 * * *
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-vscode-extensions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v15
        name: Install Nix
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Update Extensions
        run: ./modules/vscode/update_all_extensions

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'modules/vscode/shared_exts.nix'
          default_author: github_actor
          message: 'Updated Visual Studio Code extensions'
          pull_strategy: 'NO-PULL'
